{{- if and .Values.nextjs.preDeployJob.enabled (not .Values.nextjs.env.existingSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs.fullname" . }}-env-pre-deploy-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  {{- range $key, $val := .Values.nextjs.env.variables }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}

{{- end }}