apiVersion: v1
kind: Service
metadata:
  name: {{ include "freeradius.fullname" . }}
  labels:
    {{- include "freeradius.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    {{- include "freeradius.selectorLabels" . | nindent 4 }}
  ports:
    - name: radius-auth
      port: {{ .Values.service.authPort }}
      targetPort: radius-auth
      protocol: UDP
    - name: radius-acct
      port: {{ .Values.service.acctPort }}
      targetPort: radius-acct
      protocol: UDP