apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" . }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "django.fullname" . }}-env-secrets, {{ include "django.fullname" . }}-env-ext-secrets"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default "alpine" }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.nginx.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.nginx.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: socket
              mountPath: /tmp
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          {{- with .Values.nginx.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ .Chart.Name }}-django-app
          securityContext:
            {{- toYaml .Values.django.securityContext | nindent 12 }}
          image: "{{ .Values.django.image.repository }}:{{ .Values.django.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.django.image.pullPolicy }}
          command: [ "uvicorn" ]
          args: [ "--uds", "/tmp/uvicorn.sock", "--workers", "3", "main:app" ]
          envFrom:
            - secretRef:
                name: {{ include "django.fullname" . }}-env-secrets
            {{- if .Values.django.env.envFromSecretsManager.enabled }}
            - secretRef:
                name: {{ include "django.fullname" . }}-env-ext-secrets
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.django.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.django.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.django.resources | nindent 12 }}
          volumeMounts:
            - name: socket
              mountPath: /tmp
          {{- with .Values.django.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: socket
          emptyDir: { }
        - name: nginx-conf
          configMap:
            name: {{ include "django.fullname" $ }}-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      {{- with .Values.nginx.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.django.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
