{{- range $worker := $.Values.django.workers }}
{{- if $worker.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" $ }}-worker-{{ $worker.name }}
  labels:
    {{- include "django.labels" $ | nindent 4 }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "django.fullname" $ }}-env-secrets, {{ include "django.fullname" $ }}-env-ext-secrets"
spec:
  {{- if not $worker.autoscaling.enabled }}
  replicas: {{ $worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "django.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $worker.name }}
          securityContext:
            {{- toYaml $worker.securityContext | nindent 12 }}
          image: "{{ $.Values.django.image.repository }}:{{ $.Values.django.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.django.image.pullPolicy }}
          {{- if $worker.containerCommand }}
          command: {{- range $worker.containerCommand }}
            - {{ . }} {{- end}}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "django.fullname" $ }}-env-secrets
            {{- if $.Values.django.env.envFromSecretsManager.enabled }}
            - secretRef:
                name: {{ include "django.fullname" $ }}-env-ext-secrets
            {{- end }}
          livenessProbe:
            {{- toYaml $worker.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $worker.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $worker.resources | nindent 12 }}
          volumeMounts:
            {{- with $worker.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with $worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- with $worker.extraVolumes }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
{{- end }}
