{{- if .Values.django.migrationJob.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django.fullname" . }}-env-migration-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  {{- range $key, $val := .Values.env.variables }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}

{{- if .Values.django.env.envFromSecretsManager.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "django.fullname" . }}-env-migration-ext-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "django.fullname" . }}-env-migration-ext-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.django.env.envFromSecretsManager.secretPath }}
{{- end }}
{{- end }}
