apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs.fullname" . }}
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "nextjs.fullname" . }}-env-secrets, {{ include "nextjs.fullname" . }}-env-ext-secrets"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nextjs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextjs.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextjs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default "alpine" }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.nginx.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.nginx.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            {{- with .Values.nginx.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.nextjs.securityContext | nindent 12 }}
          image: "{{ .Values.nextjs.image.repository }}:{{ .Values.nextjs.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nextjs.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "nextjs.fullname" . }}-env-secrets
            {{- if .Values.nextjs.env.envFromSecretsManager.enabled }}
            - secretRef:
                name: {{ include "nextjs.fullname" . }}-env-ext-secrets
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.nextjs.port | default "3000" }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.nextjs.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.nextjs.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.nextjs.resources | nindent 12 }}
          {{- with .Values.nextjs.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "nextjs.fullname" $ }}-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      {{- with .Values.nginx.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nextjs.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
