apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnet.fullname" . }}
  labels:
    {{- include "dotnet.labels" . | nindent 4 }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ include "dotnet.fullname" . }}-env-secrets, {{ include "dotnet.fullname" . }}-env-ext-secrets"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dotnet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dotnet.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dotnet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-app
          securityContext:
            {{- toYaml .Values.dotnet.securityContext | nindent 12 }}
          image: "{{ .Values.dotnet.image.repository }}:{{ .Values.dotnet.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dotnet.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dotnet.fullname" . }}-env-secrets
            {{- if .Values.dotnet.env.envFromSecretsManager.enabled }}
            - secretRef:
                name: {{ include "dotnet.fullname" . }}-env-ext-secrets
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.dotnet.port | default "5001" }}
              protocol: TCP
          {{- if .Values.service.extraPorts }}
          {{- range .Values.service.extraPorts }}
            - name: {{ .name | default (printf "port-%d" .port) }}
              containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
          {{- end }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.dotnet.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.dotnet.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.dotnet.resources | nindent 12 }}
          {{- with .Values.dotnet.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.dotnet.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
