apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet.fullname" . }}
  labels:
    {{- include "dotnet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      name: {{ .Values.service.name | default (printf "port-%d" .Values.service.port) }}
      appProtocol: {{ .Values.service.appProtocol | default "http" }}
  {{- if .Values.service.extraPorts }}
  {{- range .Values.service.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default "http" }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default (printf "port-%d" .port) }}
      appProtocol: {{ .appProtocol | default "http" }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "dotnet.selectorLabels" . | nindent 4 }}
